#!/bin/tcsh

# No Fixup
mpirun --map-by socket:PE=3 -n 4 $1 in01 out01 
mpirun --map-by socket:PE=2 -n 6 $1 in02 out02
mpirun --map-by socket:PE=2 -n 6 $1 in03 out03
mpirun --map-by socket:PE=2 -n 4 $1 in04 out04
mpirun --map-by socket:PE=4 -n 4 $1 in05 out05
mpirun --map-by socket:PE=4 -n 4 $1 in06 out06
mpirun --map-by socket:PE=2 -n 8 $1 in07 out07
mpirun --map-by socket:PE=2 -n 8 $1 in08 out08
mpirun --map-by socket:PE=4 -n 4 $1 in09 out09
mpirun --map-by socket:PE=4 -n 4 $1 in10 out10
mpirun --map-by socket:PE=4 -n 4 $1 in11 out11
mpirun --map-by socket:PE=4 -n 4 $1 in12 out12
mpirun --map-by socket:PE=4 -n 4 $1 in13 out13
mpirun --map-by socket:PE=8 -n 1 $1 in14 out14

# Fixup
mpirun --map-by socket:PE=3 -n 4 $1 fin01 fout01 
mpirun --map-by socket:PE=2 -n 6 $1 fin02 fout02
mpirun --map-by socket:PE=2 -n 6 $1 fin03 fout03
mpirun --map-by socket:PE=2 -n 4 $1 fin04 fout04
mpirun --map-by socket:PE=4 -n 4 $1 fin05 fout05
mpirun --map-by socket:PE=4 -n 4 $1 fin06 fout06
mpirun --map-by socket:PE=2 -n 8 $1 fin07 fout07
mpirun --map-by socket:PE=2 -n 8 $1 fin08 fout08
mpirun --map-by socket:PE=4 -n 4 $1 fin09 fout09
mpirun --map-by socket:PE=4 -n 4 $1 fin10 fout10
mpirun --map-by socket:PE=4 -n 4 $1 fin11 fout11
mpirun --map-by socket:PE=4 -n 4 $1 fin12 fout12
mpirun --map-by socket:PE=4 -n 4 $1 fin13 fout13
mpirun --map-by socket:PE=8 -n 1 $1 fin14 fout14
