#!/bin/tcsh

# 1-D cases
# No Fixup
mpirun --map-by socket:PE=2 -n 1 $1 1d_mms_st.inp 1d_mms_st.old
mv -f flux 1d_mms_st.flux.old
mv -f slgg 1d_mms_st.slgg.old

mpirun --map-by socket:PE=4 -n 1 $1 1d_mms_t1.inp 1d_mms_t1.old

mpirun --map-by socket:PE=10 -n 1 $1 1d_mms_t2.inp 1d_mms_t2.old

# Fixup
mpirun --map-by socket:PE=2 -n 1 $1 1d_fixup_st.inp 1d_fixup_st.old
mv -f flux 1d_fixup_st.flux.old
mv -f slgg 1d_fixup_st.slgg.old

mpirun --map-by socket:PE=4 -n 1 $1 1d_fixup_t1.inp 1d_fixup_t1.old

mpirun --map-by socket:PE=10 -n 1 $1 1d_fixup_t2.inp 1d_fixup_t2.old


# 2-D cases
# No Fixup
mpirun --map-by socket:PE=4 -n 4 $1 2d_mms_st.inp 2d_mms_st.old
mv -f flux 2d_mms_st.flux.old
mv -f slgg 2d_mms_st.slgg.old

mpirun --map-by socket:PE=4 -n 4 $1 2d_mms_t1.inp 2d_mms_t1.old

mpirun --map-by socket:PE=4 -n 4 $1 2d_mms_t2.inp 2d_mms_t2.old

# Fixup
mpirun --map-by socket:PE=4 -n 4 $1 2d_fixup_st.inp 2d_fixup_st.old
mv -f flux 2d_fixup_st.flux.old
mv -f slgg 2d_fixup_st.slgg.old

mpirun --map-by socket:PE=4 -n 4 $1 2d_fixup_t1.inp 2d_fixup_t1.old

mpirun --map-by socket:PE=4 -n 4 $1 2d_fixup_t2.inp 2d_fixup_t2.old


# 3-D cases
# No Fixup
mpirun --map-by socket:PE=4 -n 4 $1 3d_mms_st.inp 3d_mms_st.old
mv -f flux 3d_mms_st.flux.old
mv -f slgg 3d_mms_st.slgg.old

mpirun --map-by socket:PE=2 -n 8 $1 3d_mms_t1.inp 3d_mms_t1.old

mpirun --map-by socket:PE=2 -n 8 $1 3d_mms_t2.inp 3d_mms_t2.old

mpirun --map-by socket:PE=2 -n 8 $1 3d_model.inp 3d_model.old

mpirun --map-by socket:PE=4 -n 4 $1 3d_model_n.inp 3d_model_n.old

# Fixup
mpirun --map-by socket:PE=4 -n 4 $1 3d_fixup_st.inp 3d_fixup_st.old
mv -f flux 3d_fixup_st.flux.old
mv -f slgg 3d_fixup_st.slgg.old

mpirun --map-by socket:PE=2 -n 8 $1 3d_fixup_t1.inp 3d_fixup_t1.old

mpirun --map-by socket:PE=2 -n 8 $1 3d_fixup_t2.inp 3d_fixup_t2.old

mpirun --map-by socket:PE=2 -n 8 $1 3d_mod_fixup.inp 3d_mod_fixup.old

mpirun --map-by socket:PE=4 -n 4 $1 3d_mod_fix_n.inp 3d_mod_fix_n.old

